cargo: Fix the build dependency for eaa_kbc
kbs_protocol is not required by eaa_kbc

Fix the CI lint error:
Error:   --> attestation-agent/kbs_protocol/src/client/mod.rs:37:16
   |
32 | pub struct KbsClient<T> {
   |            --------- fields in this struct
...
37 |     pub(crate) tee_key: TeeKeyPair,
   |                ^^^^^^^
38 |
39 |     pub(crate) provider: T,
   |                ^^^^^^^^
...
42 |     pub(crate) http_client: reqwest::Client,
   |                ^^^^^^^^^^^
...
45 |     pub(crate) kbs_host_url: String,
   |                ^^^^^^^^^^^^
...
48 |     pub(crate) token: Option<Token>,
   |                ^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`

Signed-off-by: Wang, Arron <arron.wang@intel.com>