gha: Do not use oras-project/setup-oras for s390x
`oras-project/setup-oras` does not support s390x like:

```
Error: Error: unsupported architecture: s390x
```

But the package is already installed and maintained by the
self-hosted runner admin.
Let's skip installing it for the platform.

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>