confidential-data-hub: drop unused structs
For some time now we have seen the following clippy errors:
error: struct `KeyWrapOutput` is never constructed
error: struct `KeyWrapResults` is never constructed

Drop them as they seem unused here.

Note: coco_keyprovider and ocicrypt-rs have their own definitions
for the same.

Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>