image-rs: fix rust 1.90 clippy warnings
the weekly 'rust stable' check started failing with rust 1.90
for image-rs due to unused-parens:

error: unnecessary parentheses around type
  --> image-rs/src/decoder/mod.rs:62:16
   |
62 |         input: (impl AsyncRead + Unpin + 'a + Send),
   |                ^                                  ^
   |
   = note: `-D unused-parens` implied by `-D warnings`

Run cargo clippy --fix -p image-rs to fix.

Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>